### ISSUE TITLE
Cannot build in angular due to bad dependency in grpc-web-client

### ISSUE THREAD

**Issue by pct-cclausen** [aiden/rpc_ts#11]
Issue is described here:

https://github.com/improbable-eng/grpc-web/issues/191

This work around helped me, but there probably is a better solution, maybe use a newer version of grpc-web?

https://github.com/improbable-eng/grpc-web/issues/191#issuecomment-392400876

**Comment by hchauvin** [comment]
Thank you for the report. I bumped the version of a few third-party dependencies, including grpc-web-client (which was renamed to `@improbable-eng/grpc-web`).

https://github.com/aiden/rpc_ts/pull/12
